# Generated by Django 3.0.8 on 2020-07-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200722_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
